words = [
    "Electromagnetics",
    "MΩ",
    "Sievert",
    "clippy",
    "fizix",
    "klx",
    "kmol",
    "mbar",
    "mmol",
    "nmol",
    "trybuild",
    "typenum",
    "udeps",
    "µg",
    "µm",
    "µmol",
    "µs",
]
