//! Integration tests for fizix demonstrating real-world physics scenarios.
//!
//! # Notes
//!
//! Compile-time dimension checking (e.g. `Meter + Second`) is verified
//! via the `trybuild` test at the bottom of this file, not via doc-tests
//! (which aren't collected from integration test crates by `cargo test`).

#![allow(clippy::float_cmp)]

use std::f64;

use fizix::*;

macro_rules! assert_display {
    ($x:expr, $pretty:literal, $ascii:literal) => {
        assert_eq!(format!("{}", $x), $pretty);
        assert_eq!(format!("{:#}", $x), $ascii);
    };
}

/// Real-world physics: calculate average speed
///
/// A car travels 1000 meters in 10 seconds.
/// Average speed = distance / time = 100.0 m/s.
#[test]
fn speed_calculation() {
    let distance = Meter::new(1000.0);
    let travel_time = Second::new(10.0);

    // Division changes the dimension from length (m) / time (s) → velocity (m⋅s⁻¹).
    // Type annotation confirms the inferred type is Velocity<f64>.
    let speed: Velocity<f64> = distance / travel_time;

    assert!(
        (speed.value - 100.0).abs() < 1e-10,
        "expected 100.0 m/s, got {}",
        speed.value
    );
}

/// Derived unit arithmetic using constants
///
/// Verify that chaining `/ SECOND` correctly builds derived dimensions.
#[test]
fn derived_unit_arithmetic() {
    // METER / SECOND / SECOND produces the Acceleration type (m⋅s⁻²)
    let acc: Acceleration<_> = METER / SECOND / SECOND;
    assert_eq!(acc.value, 1.0);

    // KILOGRAM * METER / SECOND / SECOND == NEWTON  (kg⋅m⋅s⁻²)
    assert_eq!(KILOGRAM * METER / SECOND / SECOND, NEWTON);

    // PASCAL = NEWTON / (METER * METER)  (kg⋅m⁻¹⋅s⁻²)
    assert_eq!(PASCAL, NEWTON / (METER * METER));
}

/// Helper functions and constants generated by `alias_units!`
///
/// Every named unit produces a lowercase helper function and an
/// UPPERCASE constant (with value 1.0).
#[test]
fn helper_functions_and_constants() {
    // helper functions
    let d = meter(100.0);
    let t = second(10.0);
    assert_eq!(d.value, 100.0);
    assert_eq!(t.value, 10.0);

    let m = kilogram(5.0);
    assert_eq!(m.value, 5.0);

    // constants
    assert_eq!(METER.value, 1.0);
    assert_eq!(SECOND.value, 1.0);
    assert_eq!(KILOGRAM.value, 1.0);
    assert_eq!(NEWTON.value, 1.0);
    assert_eq!(PASCAL.value, 1.0);
    assert_eq!(JOULE.value, 1.0);
    assert_eq!(WATT.value, 1.0);
}

/// Chaining multiple operations: work-energy equivalent
///
/// Force (N) * distance (m) should equal energy (J).
/// 1 N * 1 m = 1 J
#[test]
fn work_energy_relation() {
    let force: Newton<_> = NEWTON;
    let distance: Meter<_> = METER;

    let work: Joule<_> = force * distance;
    assert_eq!(work.value, 1.0);
}

/// Different numeric types work with the same unit types
#[test]
fn integer_arithmetic() {
    let d = Meter::new(1000i32);
    let t = Second::new(10i32);
    let speed = d / t;
    assert_eq!(speed.value, 100i32);
}

/// Display output for scalar (dimensionless) values
#[test]
fn display_scalar() {
    let s: Unit<f64> = Scalar::new(f64::consts::PI);
    assert_display!(s, "3.141592653589793", "3.141592653589793");
}

/// Display output from chained arithmetic
#[test]
fn display_chained_arithmetic() {
    let distance = Meter::new(1000.0);
    let time = Second::new(10.0);
    let speed = distance / time;
    assert_display!(speed, "100 m⋅s⁻¹", "100 m*s^-1");

    let work = NEWTON * METER;
    assert_display!(work, "1 kg⋅m²⋅s⁻²", "1 kg*m^2*s^-2");
}

/// Verify that adding meters and seconds is rejected at compile time.
///
/// Uses `trybuild` to compile a separate test file that attempts the
/// forbidden operation and confirms the compiler rejects it.
#[test]
fn compile_fail_dimension_mismatch() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/dimension_mismatch.rs");
}

#[test]
fn compile_fail_too_many_dims() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/too_many_dims.rs");
}

#[test]
fn compile_fail_private_alias() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/private_alias.rs");
}

#[test]
fn compile_fail_without_const() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/without_const.rs");
}

#[test]
fn compile_fail_duplicate_name() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/duplicate_name.rs");
}

#[test]
fn compile_fail_bad_dim_type() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/bad_dim_type.rs");
}

#[test]
fn compile_fail_const_wrong_position() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/const_wrong_position.rs");
}
