//! Integration tests for siunit demonstrating real-world physics scenarios.
//!
//! # Notes
//!
//! Compile-time dimension checking (e.g. `Meter + Second`) is verified
//! via the `trybuild` test at the bottom of this file, not via doc-tests
//! (which aren't collected from integration test crates by `cargo test`).

use siunit::*;

/// Real-world physics: calculate average speed
///
/// A car travels 1000 meters in 10 seconds.
/// Average speed = distance / time = 100.0 m/s.
#[test]
fn speed_calculation() {
    let distance = Meter::new(1000.0);
    let travel_time = Second::new(10.0);

    // Division changes the dimension from length (m) / time (s) → velocity (m⋅s⁻¹).
    // Type annotation confirms the inferred type is Velocity<f64>.
    let speed: Velocity<f64> = distance / travel_time;

    assert!(
        (speed.value - 100.0).abs() < 1e-10,
        "expected 100.0 m/s, got {}",
        speed.value
    );
}

/// Derived unit arithmetic using constants
///
/// Verify that chaining `/ SECOND` correctly builds derived dimensions.
#[test]
fn derived_unit_arithmetic() {
    // METER / SECOND / SECOND produces the Acceleration type (m⋅s⁻²)
    let acc: Acceleration<f64> = METER / SECOND / SECOND;
    assert_eq!(acc.value, 1.0);

    // KILOGRAM * METER / SECOND / SECOND == NEWTON  (kg⋅m⋅s⁻²)
    assert_eq!(KILOGRAM * METER / SECOND / SECOND, NEWTON);

    // PASCAL = NEWTON / (METER * METER)  (kg⋅m⁻¹⋅s⁻²)
    assert_eq!(PASCAL, NEWTON / (METER * METER));
}

/// Helper functions and constants generated by `alias_units!`
///
/// Every named unit produces a lowercase helper function and an
/// UPPERCASE constant (with value 1.0).
#[test]
fn helper_functions_and_constants() {
    // -- helper functions ---------------------------------------------------
    let d = meter(100.0);
    let t = second(10.0);
    assert_eq!(d.value, 100.0);
    assert_eq!(t.value, 10.0);

    let m = kilogram(5.0);
    assert_eq!(m.value, 5.0);

    // -- constants ----------------------------------------------------------
    assert_eq!(METER.value, 1.0);
    assert_eq!(SECOND.value, 1.0);
    assert_eq!(KILOGRAM.value, 1.0);
    assert_eq!(NEWTON.value, 1.0);
    assert_eq!(PASCAL.value, 1.0);
    assert_eq!(JOULE.value, 1.0);
    assert_eq!(WATT.value, 1.0);
}

/// Chaining multiple operations: work-energy equivalent
///
/// Force (N) * distance (m) should equal energy (J).
/// 1 N * 1 m = 1 J
#[test]
fn work_energy_relation() {
    let force: Newton<f64> = NEWTON;
    let distance: Meter<f64> = METER;

    let work: Joule<f64> = force * distance;
    assert_eq!(work.value, 1.0);
}

/// Different numeric types work with the same unit types
#[test]
fn integer_arithmetic() {
    let d = Meter::new(1000i32);
    let t = Second::new(10i32);
    let speed = d / t;
    assert_eq!(speed.value, 100i32);
}

/// Verify that adding meters and seconds is rejected at compile time.
///
/// Uses `trybuild` to compile a separate test file that attempts the
/// forbidden operation and confirms the compiler rejects it.
#[test]
fn compile_fail_dimension_mismatch() {
    let t = trybuild::TestCases::new();
    t.compile_fail("tests/compile_fail/dimension_mismatch.rs");
}
