name: Build Release Binaries
on:
  release:
    types: [published]

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.event.release.tag_name }}
          writeToFile: false

      - name: Update Release
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          body: ${{ steps.changelog.outputs.changes }}
